name: env310_journal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - numpy=1.26.4
  - pandas=2.2.0
  - networkx=3.2.1
  - geopandas=0.14.3
  - osmnx=1.9.1
  - pymoo=0.6.1.1
  - scipy=1.12.0
  - matplotlib=3.8.2
  - pip